### ISSUE TITLE
Can not install it on Hana Express

### ISSUE THREAD

**Issue by edacostacegb** [SAP/hana-shine-xsa#1]
Hello

Is there any method to install Shine XSA on Hana Express ?
I have the following error :

[INFO] Processing module shine-admin-js
[INFO] Processing module shine-xsjs
[INFO] Processing module shine-jobs-js
[ERROR] HTTP 500 Internal Server Error

********** End of /hana-shine-xsa Build Log **********
14:39:18 (Builder) Check console logs for details
14:39:18 (Builder) Build of /hana-shine-xsa failed.

Regards

Emmanuel

**Comment by viveksrinivas** [comment]
we are looking in to the issue

**Comment by CHERIANS** [comment]
Hi
Can you check if jobscheduler-broker service is STARTED
xs services | grep STOPPED
If its stopped please start it with command xs start jobscheduler-broker. For this you need to be in the Space SAP(xs target -o HANAExpress -s SAP; xs services)
Best Regards
Stephen

**Comment by CHERIANS** [comment]
Hi,
Closing issue as solution was provided.
Best Regards
Stephen
