### ISSUE TITLE
Deploy fails "shine-user-container"

### ISSUE THREAD

**Issue by draschke** [SAP/hana-shine-xsa#11]
Hi Stephen,
thanks for the hint with ui5, it solved my issue.

But now I'm struggeling with:
 **Could not validate services: Service "DIRASCHK_shine-user-container"**
Can't deploy it.

I was doing this in my mta:
    parameters: 
     service-name: DIRASCHK_shine-user-container
     config:
       schema: DIRASCHK_SHINE_USER_SCHEMA

Uploading 1 files:
 T:\com.sap.refapps.shine_1.3.4.mtar
File upload finished

Starting process xs2-deploy...
Starting monitoring...
 Validating parameters...
 Processing MTA archive...
 Processing MTA extension descriptors...
 Detecting MTA major schema version...
 MTA schema version: 3.1.0
 Detecting deploy target...
 Detected deploy target "orgname DEV"
 Validating and merging descriptors...
 Detecting deployed MTA...
 No deployed MTA detected
 Collecting system parameters...
 New MTA version: 1.3.4
 Building cloud deployment model...
 Building cloud undeployment model...
 Validating services to create...
 Could not validate services: Service "DIRASCHK_shine-user-container" already ex
ists, but is bound to application(s), not detected as part of the mta - standalo
ne apps : DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-js, DIRASCHK-x66zgfr1xba
o18pb-hana-shine-xsa-user-java
 Service "DIRASCHK_shine-user-container" already exists, but is bound to applica
tion(s), not detected as part of the mta - standalone apps : DIRASCHK-x66zgfr1xb
ao18pb-hana-shine-xsa-user-js, DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-jav
a
ERR    Could not validate services: Service "DIRASCHK_shine-user-container" alre
ady exists, but is bound to application(s), not detected as part of the mta - st
andalone apps : DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-js, DIRASCHK-x66zg
fr1xbao18pb-hana-shine-xsa-user-java
Service "DIRASCHK_shine-user-container" already exists, but is bound to applicat
ion(s), not detected as part of the mta - standalone apps : DIRASCHK-x66zgfr1xba
o18pb-hana-shine-xsa-user-js, DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-java

**Comment by CHERIANS** [comment]
Hi,
Looks like you have another app which is bound to service  DIRASCHK_shine-user-container.  May be the one which was created when you were trying with SHINE in Web IDE. You can do one of the below options
1. Delete all the service created when you were trying SHINE in Web IDE
or
2. Try deploying SHINE mtar in another space which was not used when you were trying SHINE in Web IDE
Best regards
Stephen

**Comment by draschke** [comment]
Removed the shine container services...
Any ideas ?

12:05:09 (DIBuild) Granting the schema role "user" to the principal "HANA_SHINE_XSA_SHINE_CONTAINER_1#OO" in the schema "" with grant option = "0"
Error: Granting schema roles in the container "DIRASCHK_SHINE_USER_SCHEMA_1" and the parameters "[]"... failed [8214221]
Error: Database error 389: : invalid role name: user: line 1 col 7 (at pos 6) [8201003]
Error: Error executing: CALL "DIRASCHK_SHINE_USER_SCHEMA_1#DI".GRANT_CONTAINER_SCHEMA_ROLES(#CONTAINER_ROLES, #CONTAINER_ROLES_PARAMETERS, ?, ?, ?);
(nested message: HDI call failed)
grantor service: hdi-user-service, granting user: SBSS_65101237750011136024963469597346336674807942543853802618001768946 (hdi_user)
file name: /HANA/usr_sap/CH2/xs/ea_data/saphana2/executionroot/3e6a264b-8e41-4ca9-b9d4-16de0c130daa/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-1018431104606121857/core-db/cfg/user.hdbgrants
(0s 699ms)

**Comment by draschke** [comment]
ok, got it. wrong order of building the db modul

**Comment by draschke** [comment]
Got the same issue.
Maybe the name should include the technical name?


my mta:
parameters:
service-name: DIRASCHK_shine-user-container
config:
schema: DIRASCHK_SHINE_USER_SCHEMA

**Comment by draschke** [comment]
hI Cherians, 
I don't understand the error message.
If I check the console, than I see only one bound js app to the container!?
DIRASCHK_shine-user-container                                       hana
     hdi-shared     di-builder, DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-js

**Comment by CHERIANS** [comment]
Hi,
This app DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-js seems to be deployed when you did a build and deployment of the SHINE user-js module via Web IDE. 
As far i understand now you have built the mtar via web ide and trying to deploy the mtar via XSA CLI (xs  deploy shine.mtar)
Now deploy service is also trying to create the same service ('DIRASCHK_shine-user-container') and sees an unrecognized app 'DIRASCHK-x66zgfr1xbao18pb-hana-shine-xsa-user-js' (which is not a part of mta) its throwing that error. Can you unbind the service 'DIRASCHK_shine-user-container' from all the bound apps.
The easiest way to do it is to deploy mtar into another space which you were not using with Web IDE

Best regards
Stephen

**Comment by draschke** [comment]
Hi Stephen,
thanks for this nice explanation.
Yes, I was doing what you mentioned and come over it. 
But now I'm struggling with a new issue: The starting of the "site-web" is crushing. But this is what I was keen to see running. 
[site-web_log.txt](https://github.com/SAP/hana-shine-xsa/files/1114424/site-web_log.txt)
Please could you check for it.
Thanks!

**Comment by CHERIANS** [comment]
Hi,
Thanks for update.  What is the xsa version in your system ( run command xs version from XSA CLI). Also have you changed the versions of file @sap/site-entry in package.json from the current version 1.9.6
Best Regards
Stephen

**Comment by draschke** [comment]
v1.0.55

No its   "@sap/site-entry": "1.9.6" for the shine content

I also recognized the same behavior by the prototype, if I follow this video:
https://www.youtube.com/watch?v=dCbggO5EZQc&feature=youtu.be

**Comment by draschke** [comment]
Hi Stephen,
could solve this problem after an update to XSACPORTALSERV01_1-80002098.ZIP.
Now, everything is installed and running. :)
Thanks!

**Comment by CHERIANS** [comment]
Great you could figure out the issue. Thanks for the update
Best regards
Stephen
