### ISSUE TITLE
Defining Path to Importfile in hdbtabledata

### ISSUE THREAD

**Issue by Ang3er** [SAP/hana-shine-xsa#14]
Hi there,

Iam not able to find any configuration descriptions of how to use parameters to define the path for Importfiles in the hdbtabledata, as Iam trying to achieve a folder seperation due to easier management.

Thanks in advance
Dominik

**Comment by kiruthikan** [comment]
Hi Ang3er,

Sorry for my delayed response. 
If you have namespace in your application(eg: test.abc) and you have "subfolder": "append" setting, then you can give the the file_name in your hdbtabledata like below:

**"file_name": "test.abc.data::PROJECTS.csv",**

In this case csv's are present inside the data folder.

Hope this helps.
Please let me know if you have further questions.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Closing this issue as there is no response. Please reopen in case there are any updates.
