### ISSUE TITLE
mtar deploy error

### ISSUE THREAD

**Issue by sameerPanigrahi** [SAP/hana-shine-xsa#26]
Process error: Error merging descriptors: Unsupported module type "siteentry" for platform type "CLOUD-FOUNDRY"
Use "cf deploy -i 6256769 -a retry" to retry the process
Use "cf deploy -i 6256769 -a abort" to abort the process
Use "cf dmol -i 6256769" to download the logs of the process

Could you let me know what have I missed here.
------------------------------------------------------------------------
Also, in the README.md file, changes are to be made in mta.yaml file at line 141 and 178.
But in the mta.yaml, the content at these lines are different.

Is the READ.md up to date with the changes in the code.
I have only changed the controller URL property in the mta.yaml file to point to cf endpoint URL (in cloud foundry trial)

**Comment by kiruthikan** [comment]
Hi,
I believe you are trying to deploy the master branch in your CF.
The master branch content is SHINE for XSA which is on premise.

Please clone the branch "shine-cf" and try deploying on CF.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Closing this issue. Kindly reopen if you have further questions.
