### ISSUE TITLE
Failures of user-java build

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP/hana-shine-xsa#29]
Hi. I cloned the repository to HANA Express 2 SPS2 (version: 2.00.022.00.1511184640) and following steps from https://help.sap.com/http.svc/rc/13ff61e61a8f442090e27050dc61f019/2.0.02/en-US/SAP_HANA_Interactive_Education_SHINE_for_SAP_HANA_XS_Advanced_en.pdf section 3.1.2 Deploy SHINE for XSA Application Without FLP, but in step 12 the build of user-java fails because "SAP repository" http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.milestones from pom.xml is not available publicly. And if repository removed from pom.xml, than build fails because it cannot find com.sap.gateway.v4.rt in central Maven repository. Can you fix that please?

Cc @Lsubatin

**Comment by Sygyzmundovych** [comment]
Ok, I see the answer to the closed issue https://github.com/SAP/hana-shine-xsa/issues/15#issuecomment-326492736 how to fix that, but then it should be part of the user documentation.

**Comment by kiruthikan** [comment]
Hi,

We have removed the dependency and updated the code accordingly.
Kindly try reinstalling SHINE now.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Kindly reopen if the issue still persists.
