### ISSUE TITLE
No plugin found for prefix 'dependency' in the current project and in the plugin groups : SAP HANA Shine 2.0 master error

### ISSUE THREAD

**Issue by spperumalsamy** [SAP/hana-shine-xsa#31]
[ERROR] No plugin found for prefix 'dependency' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/hana/shared/HXE/xs/app_working/hxehost/executionroot/d09b6a96-3654-4d8a-96a9-9b792d29d5ad/app/META-INF/.sap_java_buildpack/tomcat/temp/maven_repo_4074536842951125134), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by kiruthikan** [comment]
Hi,

Can you please give us more details on the issue?
In this error coming up in the java module?

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Please reopen this issue if its still present after installing the latest code.
