### ISSUE TITLE
Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user

### ISSUE THREAD

**Issue by spperumalsamy** [SAP/hana-shine-xsa#32]
Hi Team,
I am getting below error in shine XSA in GCP platform. please help me to solve the issue.

[ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.4.2: Could not find artifact com.sap.xs2.security:java-container-security:jar:0.22.2 in central (https://repo.maven.apache.org/maven2) -&gt; [Help 1]

cheers,
Sukumar

**Comment by spperumalsamy** [comment]
Hi Team, Error is coming from user-java module and below path is not exist in maven.

https://repo.maven.apache.org/maven2/com/sap/xs2/security/java-container-security/0.22.2/java-container-security-0.22.2.pom

![image](https://user-images.githubusercontent.com/35278824/34969206-c6751216-fac1-11e7-92ee-df738a0d1ede.png)

can you guys check the maven and update the relevant files.

Cheers,
Sukumar

**Comment by kiruthikan** [comment]
Hi,

This is an issue from our side. The library is not a part of maven, as you mentioned.
We have removed the dependency and updated the code accordingly.
Kindly try reinstalling SHINE now.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Please reopen this issue if its still present after installing the latest code.
