### ISSUE TITLE
Error while building MTAR file for shine-cf

### ISSUE THREAD

**Issue by vkmoorthy** [SAP/hana-shine-xsa#34]
I am trying to build the MTAR file for Shine-cf and getting the following error. I am on a Mac OS
C1MSM0LMH3QK:hana-shine-xsa-shine-cf i806119$ java -jar mta.jar --build-target=CF --mtar=shine-cf.mtar build
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/i806119/Documents/hana-shine-xsa-shine-cf/.mta/deps/guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SAP Multitarget Application Archive Builder 1.0.8
Module "shine-core-db": /Users/i806119/Documents/hana-shine-xsa-shine-cf/core-db/package.json already exists
Module "site-content": /Users/i806119/Documents/hana-shine-xsa-shine-cf/site-content/package.json already exists
Module "shine-core-db": invoking npm
Module "site-content": invoking npm
Module "shine-core-db": command output
>  npm notice created a lockfile as package-lock.json. You should commit this file.
>  added 8 packages in 4.704s
Module "shine-core-db": zipping directory shine-core-db
Module "shine-core-js": invoking npm
ERROR: Failed to build module "shine-user-js". Builder not found: "nom"
C1MSM0LMH3QK:hana-shine-xsa-shine-cf i806119$ 

Appreciate any assistance

**Comment by vkmoorthy** [comment]
One more thing I downloaded shine-cf-teched and did not have any issues building the MTAR file. Am not sure what is the difference in the two branches

**Comment by kiruthikan** [comment]
Hi,

We tried today in Mac OS. The build is successful and we could not reproduce the error.
From the error logs it looks like, there is a builder called "nom" configured somewhere.
It should be npm. 
Did you edit any of the files?
Can you clone again once more and try?
Please let me know if the same error comes up.

Thanks and Regards,
Kiruthika

**Comment by vkmoorthy** [comment]
I downloaded again and getting the same error. Why is it working for shine-cf-teched and not shine-cf?

**Comment by kiruthikan** [comment]
As you can see from the code, the two branches are different. Shine-cf also showcases Fiori Launchpad but shine-cf-teched does not contain that.

Can you please tell me which node version are you using?
Can you install node 5.12.0 and build?
You can download it from here:
https://nodejs.org/download/release/v5.12.0/

Sometimes the latest node version might give issues while building.
Please let me know.

Thanks and Regards,
Kiruthika

**Comment by vkmoorthy** [comment]
Hi, 
I am using node 6.13.0. Attached is screenshot of node version as well as mta.yaml. Appreciate your support with this. I am zipping the mta.yaml as yaml is not supported here. 
[mta.yaml.zip](https://github.com/SAP/hana-shine-xsa/files/1740802/mta.yaml.zip)
![screen shot 2018-02-20 at 10 01 10 am](https://user-images.githubusercontent.com/36552541/36434699-4dc899bc-1625-11e8-8745-758c7764590e.png)



Thanks,
Vani

**Comment by vkmoorthy** [comment]
Issue was with my yaml file. Looks like it had builder nom instead of npm . Thanks for the clue closing the issue
