### ISSUE TITLE
XSA for Shine, only problems

### ISSUE THREAD

**Issue by s0000241042** [SAP/hana-shine-xsa#38]
hello 
i wanted implement shine in xsa, version 2.0 sps03 but i get always errors. it start with the first Module
User-js
is rather a big catastrophe.
i also have the relevant documentation but all for the foxis.
thanks for your fast help.
Nick

**Comment by kiruthikan** [comment]
Hi Nick,

Please provide us more details so that we can analyse what exactly is the issue.
The error messages and/or the logs will help us to get to the bottom of the issue.
Also the build order is user-db, core-db and then the js modules. Kindly follow this order.


Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Hi Nick,

Thanks for your reply.

Could you kindly paste the core-db logs in the comments?

I am not able to see any attachments here.

Thanks and Regards,
Kiruthika

**Comment by s0000241042** [comment]
Hello Kiruthika

 

            Here the pdf file.

            Many thanks for fast help. 

            

Danke für Ihre Hilfe und Rückmeldung/Thanks for your help and feedback
Mit freundlichen Grüssen/Kind regards.

 

Nick Scherer

SAP Business Transformation Senior Consultant 
SPC Scherer & Partner GmbH | Bahnhofstrasse 13| 6403 Kuessnacht am Rigi| Switzerland

F +41 41 852 2233 | M +41 79 833 2233 | E  <mailto:nick.scherer@spc4erp.com> nick.scherer@spc4erp.com |  <http://www.spc4erp.com/> www.spc4erp.com | Skype-id: spc-ns |  <https://ch.linkedin.com/in/nick-scherer-2746013> 



Handelsregister Schwyz: CH-100.4.018.100-2 | USt-IdNr: CH-103.419.382 MWST  <https://ch.linkedin.com/in/nick-scherer-2746013> 


Please consider the impact on the environment before printing this e-mail.
Diese Nachricht kann Betriebs- oder Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts, eine Vervielfältigung oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail. Vielen Dank. 

This e-mail may contain trade secrets or privileged, undisclosed, or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying, or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation.

 

 

 

Von: Kiruthika Nithyanandan <notifications@github.com> 
Gesendet: Montag, 30. April 2018 07:15
An: SAP/hana-shine-xsa <hana-shine-xsa@noreply.github.com>
Cc: Nick Scherer <nick.scherer@spc4erp.com>; Author <author@noreply.github.com>
Betreff: Re: [SAP/hana-shine-xsa] XSA for Shine, only problems (#38)

 

Hi Nick,

Thanks for your reply.

Could you kindly paste the core-db logs in the comments?

I am not able to see any attachments here.

Thanks and Regards,
Kiruthika

**Comment by s0000241042** [comment]
Hello Kiruthika

            Sorry to disturb you. Did you find something wrong in the CORE-DB?

            You can also come into my machine with team viewer in case you need access.

            

Danke für Ihre Hilfe und Rückmeldung/Thanks for your help and feedback
Mit freundlichen Grüssen/Kind regards.

 

Nick Scherer

SAP Business Transformation Senior Consultant 
SPC Scherer & Partner GmbH | Bahnhofstrasse 13| 6403 Kuessnacht am Rigi| Switzerland

F +41 41 852 2233 | M +41 79 833 2233 | E  <mailto:nick.scherer@spc4erp.com> nick.scherer@spc4erp.com |  <http://www.spc4erp.com/> www.spc4erp.com | Skype-id: spc-ns |  <https://ch.linkedin.com/in/nick-scherer-2746013> 



Handelsregister Schwyz: CH-100.4.018.100-2 | USt-IdNr: CH-103.419.382 MWST  <https://ch.linkedin.com/in/nick-scherer-2746013> 


Please consider the impact on the environment before printing this e-mail.
Diese Nachricht kann Betriebs- oder Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts, eine Vervielfältigung oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail. Vielen Dank. 

This e-mail may contain trade secrets or privileged, undisclosed, or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying, or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation.

 

 

Von: SPC Main Account <nick.scherer@spc4erp.com> 
Gesendet: Montag, 30. April 2018 08:58
An: 'SAP/hana-shine-xsa' <reply@reply.github.com>; 'SAP/hana-shine-xsa' <hana-shine-xsa@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Betreff: AW: [SAP/hana-shine-xsa] XSA for Shine, only problems (#38)

 

            Hello Kiruthika

 

            Here the pdf file.

            Many thanks for fast help. 

            

Danke für Ihre Hilfe und Rückmeldung/Thanks for your help and feedback
Mit freundlichen Grüssen/Kind regards.

 

Nick Scherer

SAP Business Transformation Senior Consultant 
SPC Scherer & Partner GmbH | Bahnhofstrasse 13| 6403 Kuessnacht am Rigi| Switzerland

F +41 41 852 2233 | M +41 79 833 2233 | E  <mailto:nick.scherer@spc4erp.com> nick.scherer@spc4erp.com |  <http://www.spc4erp.com/> www.spc4erp.com | Skype-id: spc-ns |  <https://ch.linkedin.com/in/nick-scherer-2746013> 

Handelsregister Schwyz: CH-100.4.018.100-2 | USt-IdNr: CH-103.419.382 MWST 


Please consider the impact on the environment before printing this e-mail.
Diese Nachricht kann Betriebs- oder Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts, eine Vervielfältigung oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail. Vielen Dank. 

This e-mail may contain trade secrets or privileged, undisclosed, or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying, or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation.

 

 

 

Von: Kiruthika Nithyanandan <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Montag, 30. April 2018 07:15
An: SAP/hana-shine-xsa <hana-shine-xsa@noreply.github.com <mailto:hana-shine-xsa@noreply.github.com> >
Cc: Nick Scherer <nick.scherer@spc4erp.com <mailto:nick.scherer@spc4erp.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [SAP/hana-shine-xsa] XSA for Shine, only problems (#38)

 

Hi Nick,

Thanks for your reply.

Could you kindly paste the core-db logs in the comments?

I am not able to see any attachments here.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Closing this issue as we have discussed this via mail.
