### ISSUE TITLE
Cannot build SHINE project

### ISSUE THREAD

**Issue by mikhailandronov** [SAP/hana-shine-xsa#40]
Dear colleagues,
I set up all the tools as described in <https://blogs.sap.com/2017/07/10/deploying-shine-on-the-cloud-foundry-environment-within-sap-cloud-platform/>
I try to execute "java -jar mta.jar –build-target=CF –mtar=shine-cf.mtar build" and get a lot of error messages from gyp. Log is attached: [log.txt](https://github.com/SAP/hana-shine-xsa/files/2184542/log.txt)
Can you please explain me, how to overcome the issue?
Thank you in advance!

**Comment by kiruthikan** [comment]
Hi Mikhail,

Which version of node you are using? Kindly check that your node major version is not above 6.x.x.

If it is, please download node 6.x.x and use that to try the build again.

Kindly let me know if it helps.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Hi Mikhail,

Please downgrade node to 6.x.x and try building.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Hi Mikhail,

Kindly reopen this if the issue still persists.

Thanks and Regards,
Kiruthika
