### ISSUE TITLE
 Unknown host nexus.wdf.sap.corp 

### ISSUE THREAD

**Issue by zygimantus** [SAP/hana-shine-xsa#41]
When building this project with SAP Web IDE I am getting this error:

> [ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.5.2: Failed to collect dependencies at com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0: Failed to read artifact descriptor for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0: Could not transfer artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:pom:1.5.0 from/to release (http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.releases/): nexus.wdf.sap.corp: Unknown host nexus.wdf.sap.corp -> [Help 1]>

How to solve this issue?

**Comment by kiruthikan** [comment]
Hi,

I've adapted the code accordingly. Can you try now?

Thanks and Regards,
Kiruthika

**Comment by zygimantus** [comment]
Better, but still,

> [ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.5.2: The following artifacts could not be resolved: com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.xsa:jar:1.5.0: Could not find artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

It seems that Maven is unable to find com.sap.gateway.v4.rt:com.sap.gateway libraries, where can I get them?

**Comment by kiruthikan** [comment]
This might be because the WebIDE you are using might not come with 1.5.0 version of the gateway libraries.
To find out what version is present, right click on the java module and click on Show dependency Updates.
The console will then display the available version. 
Change to that version in user-java's pom.xml. This is the relevant line:

> <sap.gateway.version>**1.5.0**</sap.gateway.version>


For example 

![image](https://user-images.githubusercontent.com/13219609/42616759-ff1f0a9a-85cc-11e8-89e1-f8b1c4984b0d.png)

Kindly let me know if this helps.

Thanks and Regards,
Kiruthika

**Comment by zygimantus** [comment]
I tried your suggestion but it does not show the available version:

09:52:22 (DIBuild) [INFO] artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds: checking for updates from central[INFO] artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc: checking for updates from central[INFO] artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web: checking for updates from central[INFO] artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core: checking for updates from central[INFO] artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.xsa: checking for updates from central[INFO] artifact javax.servlet:javax.servlet-api: checking for updates from central[INFO] artifact org.slf4j:slf4j-simple: checking for updates from central[INFO] The following dependencies in Dependencies have newer versions:[INFO] javax.servlet:javax.servlet-api ....................... 3.0.1 -> 4.0.1[INFO] org.slf4j:slf4j-simple .......................... 1.7.7 -> 1.8.0-beta2[INFO] [INFO] ------------------------------------------------------------------------[INFO] BUILD SUCCESS[INFO] ------------------------------------------------------------------------

**Comment by kiruthikan** [comment]
HI,

Could you please tell me which version of WeBIDE you are using?

Thanks and Regards,
Kiruthika

**Comment by zygimantus** [comment]
Version: SAP Web IDE for HANA 2
SPS 03 Patch 0 ( Build 4.3.23 )

**Comment by kiruthikan** [comment]
Hi,

Sorry for the delay in my reply.
This issue seems to be coming up for a lot of people and we are currently checking as to why this is coming up.
I would keep you posted on the status.

In the meantime, you can try removing the java module references from mta and approuter and try running the rest of the application.

Let me know if you face any issues while doing this.

Thanks and Regards,
Kiruthika

**Comment by clockrun** [comment]
Hi Kiruthikan,
Why not publish these jar files to public maven repository? Or alternatively, why not build a SAP's private repository, just like what we do to NPM modules?

Regards,
Clockrun

**Comment by clockrun** [comment]
I found a workaround. 
In folder /home/hana_shared/HDB/xs/app_working/<my domain>/executionroot/8d473b2a-b13a-403e-81b0-6420cc128d2d/app/META-INF/.sap_java_buildpack/tomcat/temp/maven_repo_842699947655701273
I found these components only comes with version 1.2.3 in local repository. So after change version number in pom.xml file, it works.
I have installed WebIDE 4.3.33

**Comment by karasatishkumar** [comment]
is there a fix present for this? I have a similar issue with centralized maven repo. I tried changing pom version, but it did not work. My WebIDE version is 

Version: SAP Web IDE for HANA 2 
SPS 03 Patch 63 ( Build 4.3.63 )
