### ISSUE TITLE
SHINE on XSA : user management issue

### ISSUE THREAD

**Issue by smariotti06** [SAP/hana-shine-xsa#42]
Hi,

I have recently the latest SHINE version on SAP HANA 2.0 SPS 03.
and, offourse,  all the  pre-requisites , ie. all the XSA components required for SHINE.

Now I am not able to manage users anymore  from XSA Cockpit - user management tile.
I don't understand  how uaa service manages its different source to HANA DB, as it is now a SYSTEMDB and a TENANT DB.

all the XSA users for services are installed in the SYSTEM DB and I have installed the SHINE application in the Tenant DB.( following the space mapping )
That is maybe the issue ?

Thanks for your help.

Regards.

Stéphane MARIOTTI.

**Comment by kiruthikan** [comment]
Hi Stephane,

What do you mean by not able to manage users?
Do you get some privilege issue in SHINE?

Thanks and Regards,
Kiruthika

**Comment by smariotti06** [comment]
Hi ,

In the XSA Cockpit, I was able to update users ( assign role collection  or create new users ).

After installing, SHINE, from now I can not manage any update on any users, not only SHINE_USER

here the screen shot  
![image](https://user-images.githubusercontent.com/41191756/42690875-3cbfc8f6-86a6-11e8-8563-a4f473cacc3d.png)

**Comment by kiruthikan** [comment]
Hi,

I am not sure I understand clearly.
XSA Cockpit and SHINE are not related.Both are separate applications. 
So installing SHINE will not in anyway affect any functionality in XSA cockpit.

Also from the screenshot, I can see the New User and Edit button enabled using which you can create new users or add/remove role collections to existing users.


Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Hi Stephane,

No, SHINE is not really installed on top of XSA cockpit. XSA cockpit is a an application/tool used to manage users of all the other applications.

From the screenshot, I can now understand the problem.

Could you please tell me once which user you have logged in as?
If you have logged in as XSA_ADMIN and still not able to update, please raise an issue with XSA cockpit.

If you are logged in as SHINE_USER, you will not have permissions.
Log out and log in as XSA_ADMIN and then try updating or creating a new user.

Thanks and Regards,
Kiruthika

**Comment by smariotti06** [comment]
Hi,

I am logged in with XSA_ADMIN.

Regards.

Stéphane MARIOTTI.

**Comment by kiruthikan** [comment]
Hi Stephane,

If that is the case, kindly raise an issue with the XSA Cockpit application.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Hi Stephane,

I meant, since this issue is not related to SHINE, you can perhaps raise a support ticket with the XSA Cockpit component so that the relevant people can process it.

Thanks and Regards, 
Kiruthika

**Comment by smariotti06** [comment]
hi ,

Ok thanks
