### ISSUE TITLE
How to build the core-node?

### ISSUE THREAD

**Issue by arturgevert** [SAP/hana-shine-xsa#43]
Hi,
I have this ERROR
`16:49:08 (DIBuild) npm ERR! argv "/hana/shared/HS4/xs/app_working/hana4/executionroot/b994f7d2-fa80-47de-aca9-a08e7dd6ebdc/app/META-INF/resources/nodejs/vendor/node6.12/bin/node" "/hana/shared/HS4/xs/app_working/hana4/executionroot/b994f7d2-fa80-47de-aca9-a08e7dd6ebdc/app/META-INF/resources/nodejs/vendor/node6.12/lib/node_modules/npm/bin/npm-cli.js" "install" "--registry" "https://hana4.conogy.local:51032"npm ERR! node v6.12.2npm ERR! npm  v3.10.10npm ERR! code E404npm ERR! 404 no such package available : accept-language-parsernpm ERR! 404 npm ERR! 404  'accept-language-parser' is not in the npm registry.npm ERR! 404 You should bug the author to publish it (or use the name yourself!)npm ERR! 404 It was specified as a dependency of 'shine-core-node'npm ERR! 404 npm ERR! 404 Note that you can also install from anpm ERR! 404 tarball, folder, http url, or git url.npm ERR! Please include the following file with any support request:`

How to fix this?

**Comment by kiruthikan** [comment]
Hi,

Kindly configure your WebIDE to pick up libraries from the public npm.
You can use the following steps:

1. Login as XSA_ADMIN and switch to SAP space.
2. xs set-env di-local-npm-registry UPSTREAM_LINK http://registry.npmjs.org/
3. xs restage di-local-npm-registry
4. xs restart di-local-npm-registry
5. xs env di-local-npm-registry | grep UPSTREAM_LINK

Refresh WebIDE and rebuild the core-node module.

Thanks and Regards,
Kiruthika

**Comment by arturgevert** [comment]
Hi,
thank you very much, it works... but user-java doesn't:
Dependency Updates:
`10:52:56 (DIBuild) [WARNING] [WARNING] Some problems were encountered while building the effective model for com.sap.refapps:sap-xsac-shine-user-java:war:1.5.2[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 75, column 12[WARNING] [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.[WARNING] [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.[WARNING] [INFO]                                                                         [INFO] ------------------------------------------------------------------------[INFO] Building sap-xsac-shine-user-java 1.5.2[INFO] ------------------------------------------------------------------------[INFO] [INFO] --- versions-maven-plugin:2.5:display-dependency-updates (default-cli) @ sap-xsac-shine-user-java ---
10:52:58 (DIBuild) [INFO]   javax.servlet:javax.servlet-api ....................... 3.0.1 -> 4.0.1[INFO]   org.slf4j:slf4j-simple .......................... 1.7.7 -> 1.8.0-beta2[INFO] [INFO] ------------------------------------------------------------------------[INFO] BUILD SUCCESS[INFO] ------------------------------------------------------------------------[INFO] Total time: 3.044 s[INFO] Finished at: 2018-07-24T10:52:57+02:00[INFO] Final Memory: 12M/81M[INFO] ------------------------------------------------------------------------`

Error:
`10:59:40 (DIBuild) [WARNING] [WARNING] Some problems were encountered while building the effective model for com.sap.refapps:sap-xsac-shine-user-java:war:1.5.2[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 75, column 12[WARNING] [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.[WARNING] [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.[WARNING] [INFO] Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 KB at 26.6 KB/sec)[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 39.3 KB/sec)[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-help-plugin/maven-metadata.xml[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-help-plugin/maven-metadata.xml (590 B at 7.7 KB/sec)[INFO]                                                                         [INFO] ------------------------------------------------------------------------[INFO] Building sap-xsac-shine-user-java 1.5.2[INFO] ------------------------------------------------------------------------[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.api/1.5.0/com.sap.gateway.v4.rt.api-1.5.0.pom[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0 is missing, no dependency information available[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.core/1.5.0/com.sap.gateway.v4.rt.core-1.5.0.pom[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core:jar:1.5.0 is missing, no dependency information available[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.jdbc/1.5.0/com.sap.gateway.v4.rt.jdbc-1.5.0.pom[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc:jar:1.5.0 is missing, no dependency information available[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.cds/1.5.0/com.sap.gateway.v4.rt.cds-1.5.0.pom[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds:jar:1.5.0 is missing, no dependency information available[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.core.web/1.5.0/com.sap.gateway.v4.rt.core.web-1.5.0.pom[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web:jar:1.5.0 is missing, no dependency information available[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.xsa/1.5.0/com.sap.gateway.v4.rt.xsa-1.5.0.pom
10:59:42 (DIBuild) [INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.api/1.5.0/com.sap.gateway.v4.rt.api-1.5.0.jar[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.core/1.5.0/com.sap.gateway.v4.rt.core-1.5.0.jar[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.jdbc/1.5.0/com.sap.gateway.v4.rt.jdbc-1.5.0.jar[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.cds/1.5.0/com.sap.gateway.v4.rt.cds-1.5.0.jar[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.core.web/1.5.0/com.sap.gateway.v4.rt.core.web-1.5.0.jar[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.xsa/1.5.0/com.sap.gateway.v4.rt.xsa-1.5.0.jar[INFO]                                                                         [INFO] ------------------------------------------------------------------------[INFO] Skipping sap-xsac-shine-user-java[INFO] This project has been banned from the build due to previous failures.[INFO] ------------------------------------------------------------------------[INFO] ------------------------------------------------------------------------[INFO] BUILD FAILURE[INFO] ------------------------------------------------------------------------[INFO] Total time: 2.367 s[INFO] Finished at: 2018-07-24T10:59:40+02:00[INFO] Final Memory: 11M/80M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.5.2: The following artifacts could not be resolved: com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web:jar:1.5.0, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.xsa:jar:1.5.0: Could not find artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`
How can I fix it?
Best Regards,
Artur

**Comment by kiruthikan** [comment]
Hi Artur,

Yes, we are aware of this issue and are currently checking as to why this is coming up.
I would keep you posted on the status.

In the meantime, you can try removing the java module references from mta and approuter and try running the rest of the application.

Let me know if you face any issues while doing this.

Thanks and Regards,
Kiruthika

**Comment by arturgevert** [comment]
Hi Kiruthika, 

maybe i know the problem:
the following downlods link doesn't exist
`[INFO] Downloading: https://repo.maven.apache.org/maven2/com/sap/gateway/v4/rt/com.sap.gateway.v4.rt.api/1.5.2/com.sap.gateway.v4.rt.api-1.5.2.pom`

`[WARNING] The POM for com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.5.2 is missing, no dependency information available`

[https://repo.maven.apache.org/maven2/com/sap/](url) here is no `gateway ` folder

Best Regards,
Artur

**Comment by kiruthikan** [comment]
Hi Artur,

This library used to be packaged along with WebIDE before. 
But that does not seem to be the case in recent versions, so it is trying to download it from central maven repo (where it doesn't exist).

We are currently following it up internally as to the reason it is not packaged.

Thanks and Regards,
Kiruthika

**Comment by cosmo83** [comment]
Is this fixed by any chance ?

Iam facing the same problem.

**Comment by kiruthikan** [comment]
Hi,

Could you please try building the java module with the gateway library version 1.2.3? 

Kindly let me know if it works.

Thanks and Regards,
Kiruthika

**Comment by cosmo83** [comment]
I could build now . Thanks

**Comment by itramana** [comment]
I just tried. Not able to build even with 1.2.3. Trying from CloudFoundry. Any idea how to make it work?
8:28:04 PM (Java Build) [ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.4.3: The following artifacts could not be resolved: com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.2.3, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core:jar:1.2.3, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc:jar:1.2.3, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds:jar:1.2.3, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web:jar:1.2.3, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.xsa:jar:1.2.3, com.sap.xs2.security:java-container-security:jar:0.22.2: Could not find artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.2.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
