### ISSUE TITLE
Shine Role collection fails

### ISSUE THREAD

**Issue by manik619** [SAP/hana-shine-xsa#44]
Hi,

I have deployed the shine content in our landscape.

I am able to build and run all the modules.

However we are facing an issue. Creating Role collection in the home page fails with Authorization error even though we gave it. Could not find why it is failing. Please suggest.

![694ad326-c881-11e8-9827-ce1f82298409](https://user-images.githubusercontent.com/33085210/47062732-564ed600-d1f5-11e8-987b-b51ca17e828f.jpg)

![roles](https://user-images.githubusercontent.com/33085210/47062738-61096b00-d1f5-11e8-8b36-0584b23c71d9.jpg)

**Comment by kiruthikan** [comment]
Hi,

Do you have more than one SHINE installation in your landscape (across multiple spaces) ?

Thanks and Regards,
Kiruthika

**Comment by manik619** [comment]
Hi Kiruthika,

No, I am deploying in the system for the first time.

Thanks
Mani

**Comment by kiruthikan** [comment]
Hi Mani,

Can you try logging in as XSA_ADMIN? (if you have the credentials).
This is just to check if there are any missing privileges.

Also, can you execute the following command in the CLI, "xs  logs <shine-web app name> --recent" and post the output of it here?
It will help us get to the bottom of this.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
As discussed offline, this has now bwtween released.

**Comment by salahchakchouki** [comment]
Hi @kiruthikan I am keen to get the solution for this one as I faced the same.
I opened a ticket yesterday with the same symptom
