### ISSUE TITLE
Deploy shine-core-db fails

### ISSUE THREAD

**Issue by 802256** [SAP/hana-shine-xsa#45]
Dear experts,

I am trying to deploy SHINE on SAP HANA EXPRESS 2.0 system. The deployment process seems to work fine until the task below:

"Executing task "deploy" on application "shine-core-db"...
 Task execution status: running
 Task execution status: failed
 Error executing task "deploy" on application "shine-core-db"
 Unexpected error: Async execution has failed
ERR    Error executing task "deploy" on application "shine-core-db"
Unexpected error: Async execution has failed"
[MAIN_LOG.txt](https://github.com/SAP/hana-shine-xsa/files/2494935/MAIN_LOG.txt)

See attached log file. 

Thanks in advance!

Kind regards,
Geir Kronkvist

**Comment by LakshmiCR** [comment]
Hi Geir,

Kindly execute the command "xs logs shine-core-db --recent" and share the output logs.
This will help us analyse the issue better.

Thanks and Regards,
Lakshmi

**Comment by CHERIANS** [comment]
Closing this issues as we did not get a response. Feel free to reopen if its still relevent.
Best Regards
Stephen
