### ISSUE TITLE
An error occured while checking your authorization. 

### ISSUE THREAD

**Issue by salahchakchouki** [SAP/hana-shine-xsa#46]
Hi

Managed to launch the "launchpad" app but got the following error when tried to check the prerequisites.
`An error occured while checking your authorization.  Please assign the XS_AUTHORIZATION_ADMIN role collection to your user and retry.`
As per below screenshot, the  Role collection was already assinged.
Thank you for your support
![image](https://user-images.githubusercontent.com/43603915/47719320-0f2c0080-dc4b-11e8-952d-952be6cc7e39.png)

**Comment by CHERIANS** [comment]
Can you clarify if you are  installing shine via  web ide or SCA
Best Regards
Stephen

**Comment by salahchakchouki** [comment]
Hi @CHERIANS 
This one was through the web ide

**Comment by salahchakchouki** [comment]
I should probably reinstall by I am quite sure I removed the "extra" / and put `https://hxehost:39032/uaa-security`

Maybe that was my mistake?

**Comment by CHERIANS** [comment]
Hi,
I hope the issue was solved. Hence closing the issue. Feel free to reopen if this issue still exists
Best Regards
Stephen
