### ISSUE TITLE
Generate Time Data did not work

### ISSUE THREAD

**Issue by salahchakchouki** [SAP/hana-shine-xsa#47]
Hi,

I installed the prepackaged shine.tgz that was part of  the HXE (server+applications) from the GCP marketplace (HANA 2.0 SP03 - last updated 10/22/18, 8:15 PM)

![image](https://user-images.githubusercontent.com/43603915/47776378-92546180-dcf2-11e8-88ae-3f615c8fd7a9.png)
But when I click on the Generate Time Data, it does not work.
Any tips on when I could get some logs?

Thanks

**Comment by CHERIANS** [comment]
Hi,
Can you share the logs for shine-core-node by running below command from CLI xs logs shine-core-node --recent
Best Regards
Stephen

**Comment by salahchakchouki** [comment]
There you go: this one through SCA
Connected, dumping recent logs for app "shine-core-node"
10/30/18 5:27:48.948 PM [STG/1] OUT   Node.js
10/30/18 5:27:49.566 PM [STG/1] OUT   Node.js buildpack version 3.4.7
10/30/18 5:27:49.569 PM [STG/1] OUT   Available Node.js runtimes: node8.11,node6.14
10/30/18 5:27:50.054 PM [STG/1] OUT   Npm install not needed - attempting partial runtime download
10/30/18 5:27:50.055 PM [STG/1] OUT   Downloading Node.js...
10/30/18 5:27:50.278 PM [STG/1] OUT   Unpacking Node.js archive...
10/30/18 5:27:50.287 PM [STG/1] OUT   Omitting npm install: node_modules directory is already present and rebuild is not enabled, using dependencies as provided
10/30/18 5:27:50.288 PM [STG/1] OUT   Copying SSL CA certificates...
10/30/18 5:27:50.302 PM [STG/1] OUT   Copying SSL CA certificates to NodeExtraCAFile...
10/30/18 5:28:13.580 PM [APP/1-0] OUT    HTTP Server: 50048
10/30/18 5:58:42.000 PM [RTR] OUT    127.0.0.1 - - to hxehost:51052 "GET /sap/bc/lrep/flex/data/shine.democontent.epm.usercrud.Component HTTP/1.1" 200 sent 94 in 196 by 014-a26a29ad-5456-4bb5-8cc5-a032d4025e35

**Comment by CHERIANS** [comment]
Hi,
Can you share the logs shine-core-xsjs. Also may be try once more.
Best regards
Stephen

**Comment by salahchakchouki** [comment]
good catch @CHERIANS I tried again - I see a nice 500

```
10/31/18 10:59:19.000 AM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/poWorklistQuery.xsjs?cmd=getTotalOrders&groupby=COMPANYNAME&currency=USD&filterterms=
 HTTP/1.1" 200 sent 261 in 189 by 012-397404fb-bdcd-49bb-8250-d772cb6bf69e
10/31/18 10:59:31.000 AM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/poWorklistQuery.xsjs?cmd=getTotalOrders&groupby=CATEGORY&currency=USD&filterterms= HT
TP/1.1" 200 sent 241 in 75 by 012-397404fb-bdcd-49bb-8250-d772cb6bf69e
10/31/18 11:02:06.000 AM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/poWorklistQuery.xsjs?cmd=getTotalOrders&groupby=PRODUCTID&currency=USD&filterterms= H
TTP/1.1" 200 sent 210 in 116 by 012-397404fb-bdcd-49bb-8250-d772cb6bf69e
10/31/18 11:02:16.000 AM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/poWorklist.xsodata/PO_WORKLIST?$skip=106&$top=100 HTTP/1.1" 200 sent 3877 in 141 by 0
12-397404fb-bdcd-49bb-8250-d772cb6bf69e
10/31/18 12:00:50.000 PM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/checkTimeData.xsjs HTTP/1.1" 500 sent 28 in 26 by 012-397404fb-bdcd-49bb-8250-d772cb6
bf69e
10/31/18 12:00:50.059 PM [APP/1-0] OUT    Data unavailable
10/31/18 12:00:52.000 PM [RTR] OUT    127.0.0.1 - - to hxehost:51030 "GET /sap/hana/democontent/epm/services/generateTimeData.xsjs HTTP/1.1" 500 sent 9 in 15 by 012-397404fb-bdcd-49bb-8250-d772c
b6bf69e

```
Here's what I get on the shine-core-node

**Comment by salahchakchouki** [comment]
Unfortunately not so far


On 09 Nov 2018 11:42 AM, "kamarajanpkb" <notifications@github.com> wrote:

Hi,

I get the exact same issue. SHINE fails during time data generate option.
Any solution found?
[image: shine_error]
<https://user-images.githubusercontent.com/44792895/48258037-29d25680-e44f-11e8-8cc0-0c40d8341f96.PNG>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SAP/hana-shine-xsa/issues/47#issuecomment-437321232>,
or mute the thread

**Comment by CHERIANS** [comment]
We are investigating this issue and will update once we have a solution..
Best Regards
Stephen

**Comment by salahchakchouki** [comment]
Thanks Stephen

**Comment by LakshmiCR** [comment]
Hello All,

We are looking into the issue. Meanwhile we have a workaround for you.
Please find the steps below:
1. Open WebIDE from Hana Express and Click on the HRTT icon as shown below. Click on the '+' icon to add the Shine HDI container.
![1_hrtt](https://user-images.githubusercontent.com/20553615/48532535-d173dc80-e8c6-11e8-91cc-f4cb9f6d0e1f.jpg)

2. Select Shine HDI container as shown below
<img width="864" alt="2_shine_hdi jpg" src="https://user-images.githubusercontent.com/20553615/48532539-d6389080-e8c6-11e8-90d4-de18bfe324c5.png">

3. Select the shine container in the hrtt window and open sql console
![3_sql_console](https://user-images.githubusercontent.com/20553615/48532545-dafd4480-e8c6-11e8-9efc-7052544e4c8d.jpg)

4. Run the query :
SELECT CURRENT_SCHEMA FROM DUMMY;
5. Copy the result and replace <schema_name> in the query below :
MDX UPDATE TIME DIMENSION HOUR 2011 2017  MONDAY TARGET_TABLE "Core.SHINE_TIME_DIM" TARGET_SCHEMA "<schema_name>";
 
Now refresh your SHINE application.
The prerequisites will now be met and you can continue exploring SHINE.

Thanks and Regards,
Lakshmi

**Comment by salahchakchouki** [comment]
Thank you Lakshmi - I'll have a look & revert to confirm - probably over
the weekend.
Is it too much to ask for a planning on when would you update the appliance
on Google marketplace?
Regards,
Salah

**Comment by LakshmiCR** [comment]
We'll get back to you on this Salah.

Thanks and Regards,
Lakshmi

**Comment by noorshaikh** [comment]
Thank you for the update.  Waiting for a permanent fix.

**Comment by salahchakchouki** [comment]
Hi guys
Happy New Year
Not sure this is the right thread for such a message but the GCP appliance
does not deploy any longer
Is there an update ongoing on the Google Marketplace?
cf. below what I get when I try to deploy
Regards,
Salah


sap-hanaexpress-serverinclapps-1 has resource warnings
sap-hanaexpress-serverinclapps-1-vm:
{"ResourceType":"compute.v1.instance","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"Invalid
value for field 'resource.disks[0].initializeParams.sourceImage': '
https://www.googleapis.com/compute/v1/projects/sap-public/global/images/sap-hanaexpress-serverinclapps-suselinux12-20003300201810152'.
The referenced image resource cannot be
found.","reason":"invalid"}],"message":"Invalid value for field
'resource.disks[0].initializeParams.sourceImage': '
https://www.googleapis.com/compute/v1/projects/sap-public/global/images/sap-hanaexpress-serverinclapps-suselinux12-20003300201810152'.
The referenced image resource cannot be found.","statusMessage":"Bad
Request","requestPath":"
https://www.googleapis.com/compute/v1/projects/sap-hana-217321/zones/us-central1-f/instances
","httpMethod":"POST"}}

**Comment by CHERIANS** [comment]
@noorshaikh @salahchakchouki , this issue on Generate Time Data in SHINE was traced to HANA issue and is being fixed. Will update once the fix is available

**Comment by CHERIANS** [comment]
Hi,
This issue is fixed and this feature works fine in HANA2.0 SPS04 release of SHINE. Hence closing this issue.
Best Regards
Stephen
