### ISSUE TITLE
UAA URL in CF enterprise account

### ISSUE THREAD

**Issue by i040723** [SAP/hana-shine-xsa#48]
Where do we find the UAA endpoint URL outlined in 3.1.2 - Step 12 of SAP HANA Interactive Education (SHINE) for SAP HANA 2.0 SPS03 for SAP HANA XS Advanced Model - Document version 1.7 – 2018/09/06.

Is it same as API endpoint of the region?

**Comment by LakshmiCR** [comment]
Hi,
To find the UAA endpoint URL, please run the command "xs version" in the CLI. In the output you'll find url listed against "authorizationEndpoint".

Thanks and Regards,
Lakshmi

**Comment by i040723** [comment]
Hi Lakshmi, This is not on-premise HANA but HANA 2.0 instance in SCP CF environment.
Do you have similar commands in CF CLI or web interface to find the UAA endpoint URL?

**Comment by CHERIANS** [comment]
The complete SHINE cannot be run on SCP CF. We have an adapted version of SHINE for CF environment in the shine-cf branch of this repository. Please try that.
Best Regards
Stephen

**Comment by LakshmiCR** [comment]
As this issue has been clarified by Stephen, we are closing the issue.
Regards,
Lakshmi
