### ISSUE TITLE
Combination of $filter and $expand is not working on OData service

### ISSUE THREAD

**Issue by korayyersel** [SAP/hana-shine-xsa#49]
Hello,
We are trying to run a filter query on our OData service generated by hana-shine-xsa. It looks like this:

- zugfahrt > Parent Entity

- betriebspunktdurchfahrten > Child Entity

**CDS Definition**
```
   entity zugfahrt {
        key ID                        : String(120);
            Betriebstag               : LocalDate;
            TrassenId                 : String(16);
            Zugnummer                 : String(20);
            evu                       : String(16);
            betriebspunktdurchfahrten : association[*] to betriebspunktdurchfahrt on betriebspunktdurchfahrten.ZugfahrtID = ID;
    }
```

**OData Calls:**

- /zugfahrt?$filter=Betriebstag%20eq%202018-12-12 > works fine, no expand implemented.

 - /zugfahrt?$filter=Betriebstag%20eq%202018-12-12&$expand=betriebspunktdurchfahrten > _**does not work (see error below)**_,  filter on parent entity with expand

- /zugfahrt?$expand=betriebspunktdurchfahrten($filter=Position%20eq%201) > works fine, filter on child entity with expand

Combination of expand and filter should be possible:
https://services.odata.org/V4/Northwind/Northwind.svc/Orders?$expand=Order_Details&$filter=ShipCity%20eq%20%27Reims%27

**Error Logs**
> 12/11/18 11:13:00.656 AM [APP/1-0] ERR    com.sap.gateway.v4.rt.cds.exception.CDSRuntimeException: SAP DBTech JDBC: [257] (at 909): sql syntax error: CDS error: Syntax error: unexpected token ".": line 1 col 910 (at pos 909) CDS Query failed :SELECT FROM eva.zugfahrt AS ROOT_ENTITY_ALIAS{ID AS ZZID,Betriebstag AS ZZBetriebstag,TrassenId AS ZZTrassenId,Zugnummer AS ZZZugnummer,evu AS ZZevu,betriebspunktdurchfahrten.{ID AS betriebspunktdurchfahrtenZZID,zugehoerigeAbschnitte AS betriebspunktdurchfahrtenZZzugehoerigeAbschnitte,ZugfahrtID AS betriebspunktdurchfahrtenZZZugfahrtID,Position AS betriebspunktdurchfahrtenZZPosition,UicCode AS betriebspunktdurchfahrtenZZUicCode,UicLaenderCode AS betriebspunktdurchfahrtenZZUicLaenderCode,AnPlan AS betriebspunktdurchfahrtenZZAnPlan,AbPlan AS betriebspunktdurchfahrtenZZAbPlan,AnPrognose AS betriebspunktdurchfahrtenZZAnPrognose,AbPrognose AS betriebspunktdurchfahrtenZZAbPrognose,AnIstZeit AS betriebspunktdurchfahrtenZZAnIstZeit,AbIstZeit AS betriebspunktdurchfahrtenZZAbIstZeit}} WHERE ( ROOT_ENTITY_ALIAS.Betriebstag = '2018-12-12' )  AND ROOT_ENTITY_ALIAS.ID IN ( SELECT FROM eva.zugfahrt{ID} WHERE ( .Betriebstag = '2018-12-12' )  ORDER BY  ID ASC LIMIT 1000 OFFSET 0 )  ORDER BY  ZZID ASC, betriebspunktdurchfahrtenZZID ASC
12/11/18 11:13:00.656 AM [APP/1-0] ERR    	at com.sap.gateway.v4.rt.cds.ODataToCDSProcessor.execute(ODataToCDSProcessor.java:82) ~[com.sap.gateway.v4.rt.cds-1.2.3.jar:na]

Can you please advise? I have seen this issue https://github.com/SAP/olingo-jpa-processor-v4/issues/21 But I was not sure if it was relevant.

Regards,
Koray

**Comment by zygimantus** [comment]
I think this is not supported for Odata V2, see this link: https://answers.sap.com/questions/306661/ui5odata-filter-on-deep-entity.html?childToView=308923#answer-308923

**Comment by korayyersel** [comment]
yes you are right but we are using OData V4 not V2. see com.sap.gateway.v4.rt.cds.exception.CDSRuntimeException

**Comment by gregorwolf** [comment]
Dear @korayyersel I would suggest you provide this as an example with the Bookstore data model and share it on Github so it's easy to replicate if the issue still is there with the current cds version.

**Comment by korayyersel** [comment]
Hi Gregor, that was a good idea, thanks a lot. I have create two different MTAs with Java and OData service modules. Both worked fine. I have tried the feature with the following url pattern:
https://[root_url]/catalog/Books?$filter=title%20eq%20%27book%201%27&$expand=author

As far as I understand the new CDS Java libariries are completely different then my question from january. The new generated code imports classes from com.**sap.cloud.sdk.service.prov.api**
