### ISSUE TITLE
core-db initial build fails

### ISSUE THREAD

**Issue by i045928** [SAP/hana-shine-xsa#53]
Build of core-db fails with:
Processing "cfg/user.hdbgrants"...  Using service "hdi-user-service" of type "hdi" Granting schema roles in the container "SHINE_USER_1" and the parameters "[]"...  Granting the schema role "user" to the principal "SHINE_CORE_1#OO" in the schema "" with grant option = "false" Error: Granting schema roles in the container "SHINE_USER_1" and the parameters "[]"... failed [8214221] Error: Database error 389: : invalid role name: user: line 1 col 7 (at pos 6) [8201003]Error: Error executing: CALL "SHINE_USER_1#DI".GRANT_CONTAINER_SCHEMA_ROLES(#CONTAINER_ROLES, #CONTAINER_ROLES_PARAMETERS, ?, ?, ?); (nested message: HDI call failed)grantor service: "hdi-user-service", type: "hdi", user: "SHINE_USER_1_03TMQLXLQRZSAH39ORZ98V1B5_DT" (hdi_user)file name: /hana/shared/PQX/xs/app_working/hana-sp03test/executionroot/736fbb1a-0013-46cf-a685-2080a0ec5037/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/hdi-builder/builds/build-9218833060414168948/hana-shine-xsa/core-db/cfg/user.hdbgrants(0s 427ms)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! shine-core-db@1.6.1 start: `node node_modules/@sap/hdi-deploy/deploy.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the shine-core-db@1.6.1 start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bbiswal333** [comment]
Hi,

Based on above error logs, it seems you have build core-db without building user-db. For successfull build, please build **user-db** then **core-db**. 
For more details you can follow the SHINE documentation: https://help.sap.com/doc/13ff61e61a8f442090e27050dc61f019/2.0.04/en-US/SAP_HANA_Interactive_Education_SHINE_for_SAP_HANA_XS_Advanced_en_HANA2.0SPS04.pdf 
(chapter: 3.1.2 Deploy SHINE for XSA Application Without FLP --> step-14)

Thanks & Regards,
Bismay
