### ISSUE TITLE
Error creating service for HANA 2.0

### ISSUE THREAD

**Issue by biship** [SAP/hana-shine-xsa#6]
I've doubled checked every single command preceding this, and it looks all set up correctly. I also the steps verified against https://help.sap.com/doc/21bd6e2efc784ef19661c6302a0e83ae/2.0.00/en-US/SAP_HANA_Interactive_Education_SHINE_for_SAP_HANA_XS_Advanced_en.pdf

Any idea on what's wrong?

```
xs create-service xsuaa default shine-uaa -c xs-security.json
Creating service "shine-uaa"...
FAILED:  Error parsing service broker parameters (must be JSON format):
Unrecognized token 'xs': was expecting ('true', 'false' or 'null')
 at [Source: xs-security.json; line: 1, column: 3]
```

The only xs-security.json file I can find:
/hana/shared/HDB/xs/controller_data/fss/0e1325b7-3e5c-437e-958e-afff2d8d9c55/60/8b/69/workspaceu9vle733n23airsw/hana-shine-xsa/xs-security.json

```
{
  "xsappname": "shine-admin",
  "scopes": [
    {
      "name": "$XSAPPNAME.Display",
      "description": "display"
    },
    {
      "name": "$XSAPPNAME.Edit",
      "description": "edit"
    },
    {
      "name": "$XSAPPNAME.Delete",
      "description": "delete"
    },
    {
      "name": "$XSAPPNAME.DataGenerator",
      "description": "data generator"
    },
    {
      "name": "xs_authorization.read",
      "description": "Read authorization information from UAA"
    },
    {
      "name": "xs_authorization.write",
      "description": "Write authorization information to UAA"
    }
  ],
  "role-templates": [
    {
      "name": "Admin",
      "description": "refapps administrator",
      "scope-references": [
        "$XSAPPNAME.Display",
        "$XSAPPNAME.Edit",
        "$XSAPPNAME.Delete",
        "$XSAPPNAME.DataGenerator",
        "xs_authorization.read",
        "xs_authorization.write"
      ]
    }
  ]
}
```

**Comment by kiruthikan** [comment]
Hi,

The xs-security.json file is available in this repository itself.
https://github.com/SAP/hana-shine-xsa/blob/master/xs-security.json

While creating the shine-uaa service , the command expects the xs-security.json to be in the current folder.
If it is not then the command would have to include the path to xs-security.json. For example, in your case, it would be:

`xs create-service xsuaa default shine-uaa -c /hana/shared/HDB/xs/controller_data/fss/0e1325b7-3e5c-437e-958e-afff2d8d9c55/60/8b/69/workspaceu9vle733n23airsw/hana-shine-xsa/xs-security.json`

If the path is too big, then you can create the xs-security.json in your current path and execute the command:

`xs create-service xsuaa default shine-uaa -c xs-security.json`

I hope this is helpful.
Please let me know if there are any more issues.

Thanks and Regards,
Kiruthika

**Comment by biship** [comment]
Ah, thanks, yes that worked. I didn't realise that I had to download and place the json file into the cwd. Thanks.
