### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by zygimantus** [SAP/hana-shine-xsa#61]
I just noticed one issue with xsjs >= 4.0.0, after updating it from 3.7.0 the Validation Exit with SQLScript are not working anymore and they give this error:

> ...node_modules\@sap\xsjs\node_modules\@sap\xsodata\lib\processor\exitProcessor.js:182
>                         if (outTable.length > 0) {
>                                      ^
> 
>                         if (outTable.length > 0) {
>                                      ^
> 
> TypeError: Cannot read property 'length' of undefined

I looked at this project and procedure for Validation Exit (procedures::usersCreateMethod) is also commented out https://github.com/SAP/hana-shine-xsa/blob/master/user-xsjs/lib/user/xsodata/user.xsodata does this mean that it does not work either here?

**Comment by CHERIANS** [comment]
Hi,
We will check this and get back.
Best Regards
Stephen

**Comment by zygimantus** [comment]
Thank you.

**Comment by Kyubu-77** [comment]
Hello zygimantus,

create using "user.xsjs:userExit.xsjslib::my_create_after_exit";
seems not to provide an error table output. 

Could you please create an odata error table, an odata error structure and use this in the procedure?

There is an sample in:
https://help.sap.com/doc/PRODUCTION/fbb802faa34440b39a5b6e3814c6d3b5/2.0.00/en-US/SAP_HANA_Developer_Guide_for_SAP_HANA_Studio_en.pdf
in chapter
7.1.6.14  Tutorial: Creating a Modification Exit with SQLScript

thanks and kind regards,
Sven

**Comment by zygimantus** [comment]
Well, basically I am writing about this problem with a procedure exit, not xsjslib one:
create using "procedures::usersCreateMethod

**Comment by Kyubu-77** [comment]
Yes, the chapter 7.1.6.14 Tutorial: Creating a Modification Exit with SQLScript
describe such a stored procedure E.g.:
procedure "ODATA_TEST"."sample.odata::createmethod"
 (IN new "sample.odata::table", OUT error "sample.odata::error")
language sqlscript
sql security invoker as
 id INT;
begin
 select ID into id from :new;
 if :id < 1000 then
 error = select 400 as http_status_code,
 'invalid ID' error_message,
 'value must be >= 1000' detail from dummy;
 else
 insert into "sample.odata::table" values (:id);
 end if;
end;

**Comment by zygimantus** [comment]
Nevermind. I can see that this issue is fixed with xsjs 5.2.3 version.
