### ISSUE TITLE
SAP Gateway version in java POM file is incorrect for XSA 2.0 SPS01 (HANA EXPRESS edition)

### ISSUE THREAD

**Issue by apratasenia** [SAP/hana-shine-xsa#7]
Hi, i figured out that version of SAP Gateway in POM file issuing problems while building Java module SHINE application on SAP HANA Express SPS01, changing the version to 1.2.1 soliving the problem, please take care of it. 
 <properties>
    <sap.gateway.version>1.2.1</sap.gateway.version>

**Comment by CHERIANS** [comment]
Fixed in the  release of SHINE code for HANA 2.0 SPS01
