### ISSUE TITLE
No appropriate build pack found

### ISSUE THREAD

**Issue by JohnB12C** [SAP/hana-shine-xsa#8]
Hello,

May I ask for your guidance?   

Using the supplied source code (with modifications made as suggested that would be specific to my environment) a build was successful.  The gateway did have to be changed from 1.2.2 to 1.2.1.

The deployment produced an error related to the JAVA as follows:

      Uploading application "shine-user-java"...
      Matched files count: 1
      Matched resources processed, total size is 3,166,296
      Upload status: finished
      Scaling application "shine-user-java"...
      Staging application "shine-user-java"...
      Jun 26, 2017 11:02:05 AM com.sap.xs.java.buildpack.util.ConfigurationUtil mergeMaps
      WARNING: User config value for 'tomcat/webapps/ROOT/META-INF/context.xml' is not valid, existing property not present.
      No appropriate build pack found
      Failed to stage app 'shine-user-java' [Org 'HANAExpress', Space 'SAP']: No appropriate build pack found.
      Error staging application "shine-user-java": 200 Application staging failed
      ERR    Error staging application "shine-user-java": 200 Application staging failed

xs buildpacks shows sap_java_buildpack at version 1.6.2 at position 1 and enabled.  (environment is HXE 2 SPS01)

May I ask for your thoughts as to what to try next to successfully deploy the XSA SHINE application?

Thank you,
John

**Comment by CHERIANS** [comment]
Hi John,
Can you tell me the HANA XSA version which there in your system. Run the command 'xs version' from CLI to find XSA version.
Best regards
Stephen

**Comment by JohnB12C** [comment]
Hi Stephen,

Thanks for the reply.

The version that appeared when running the ‘xs version’ command is:   1.0.55.288028

Please let me know if I may provide any additional information.

And, thank you again for your assistance.

Best regards,
John

**Comment by CHERIANS** [comment]
Hi John,
Thanks for the info. I tried on HANA Express system with XSA Ver 1.0.55 and it worked for me. Can you give some more information to help me analyze the issue.
1. Are you working under proxy, so was the proxy settings as described in the HANA Express documentation done
2. Did you make any changes to the SHINE mta.yaml other than the once mentioned in the documentation. 
3. Are you building the complete project to get the mtar and deploying mtar  or are you just building and deploying java module from Web IDE.

Best Regards
Stephen

**Comment by JohnB12C** [comment]
Hi Stephen,

Thanks for your confirmation (works on v 1.0.55) and, of course, your time.

To answer your questions:

1)      We are set up with a proxy server to access the internet within the organization.  Though, the settings weren’t needed to access the cockpit.  Anyhow, I went ahead and entered the proxy server and port through the cockpit for the http(s) entry and enabled it.  Then, went through the build process with web ide (it was successful) and the copying of the mtar and subsequent deployment (failed again on the version of the java buildpack – which is 1.6.2).

2)      I believe that I made only the required changes to the mta.yaml  and pom.xml file (as per the SHINE docs – especially the replacement of the <SHINE_USER>).  I may have taken things too literal – so, I’ve attached the mta.yaml and pom.xml.

3)      Yes, I’m building the complete project to get the mtar, exporting it to my local machine.  Then, the mtar file gets copied to the HXE server and from the HXE server’s command prompt (access via PuTTY) I’m running the command: xs deploy com.sap.refapps.shine_1.3.4.mtar

Please let me know what other information I may provide you.

And again, thank you for your time!,
John

**Comment by CHERIANS** [comment]
Hi John,
Thanks for the update. Can you try adding the below to mta.yaml for shine-user-java module
**parameters:
     buildpack : sap_java_buildpack**
It should now look like
 \- name: shine-user-java
    type: java
    path: user-java
    provides: 
      - name: user-java
        properties:
          url: "${default-url}"
    requires:
      - name: shine-uaa
      - name: shine-scheduler
      - name: shine-user-db
      - name: shine-user-container
        properties:
         JBP_CONFIG_RESOURCE_CONFIGURATION: '[tomcat/webapps/ROOT/META-INF/context.xml:
               {"service_name_for_DefaultDB" : "~{user-container-name}"}]'
    parameters:
     buildpack : sap_java_buildpack

After this do a build in Web IDE and deploy and let me know if it works.
Best regards
Stephen

**Comment by JohnB12C** [comment]
Hi Stephen,

Thanks for the quick reply and advice.

After adding the buildpack parameter the build was once again successful yet the deployment was not.

Here’s the mta.yml entry for shine-user-java
  - name: shine-user-java
    type: java
    path: user-java
    provides:
      - name: user-java
        properties:
          url: "${default-url}"
    requires:
      - name: shine-uaa
      - name: shine-scheduler
      - name: shine-user-db
      - name: shine-user-container
        properties:
         JBP_CONFIG_RESOURCE_CONFIGURATION: '[tomcat/webapps/ROOT/META-INF/context.xml:
         {"service_name_for_DefaultDB" : "~{user-container-name}"}]'
    parameters:
       buildpack: sap_java_buildpack

And, here are the messages displayed during the deployment as it relates to the java module.

Checking application "shine-user-java"...
Application "shine-user-java" exists
Updating application "shine-user-java"...
Service "shine-uaa" will not be rebound to application "shine-user-java" because the binding parameters are not modified
Service "shine-scheduler" will not be rebound to application "shine-user-java" because the binding parameters are not modified
Service "SHINE_USER_shine-user-container" will not be rebound to application "shine-user-java" because the binding parameters are not modified
Application "shine-user-java" is not modified and will not be updated
Uploading application "shine-user-java"...
Matched files count: 1
Matched resources processed, total size is 3,166,297
Upload status: finished
Scaling application "shine-user-java"...
Staging application "shine-user-java"...
Jul 07, 2017 7:37:01 AM com.sap.xs.java.buildpack.util.ConfigurationUtil mergeMaps
WARNING: User config value for 'tomcat/webapps/ROOT/META-INF/context.xml' is not valid, existing property not present.
Specified custom build pack failed to detect the application
Failed to stage app 'shine-user-java' [Org 'HANAExpress', Space 'SAP']: Specified custom build pack failed to detect the application.
Error staging application "shine-user-java": 200 Application staging failed
ERR    Error staging application "shine-user-java": 200 Application staging failed

I don’t want to consume too much more of your valuable time – though, if you can see something obvious please let me know.

Thanks again and best regards,
John

**Comment by CHERIANS** [comment]
Hi John,
Thanks for the update. No problems at all. Would be happy to help. Feel free to raise question and provide feedback
A colleague of mine was able to reproduce the issue, but the code which i sent you (to explicitly set the  buildpack) worked for me but for my colleague it does not work. So wanted to check if it helps for you. Let me check internally and get back to you if i can find a solution.
Best Regards
Stephen

**Comment by JohnB12C** [comment]
Hi Stephen,
Again, thank you so much for your time.
If you do find out more information after checking internally of course I’d appreciate any advice.
Thank you once again,
John

**Comment by CHERIANS** [comment]
Hi John,
Sorry to get back to you late. Did you by any chance try it in HANA Express with HANA 2.0 SPS02.
Best regards
Stephen

**Comment by JohnB12C** [comment]
Hi Stephen,
Thanks for the email.  And yes, I have tried HANA Express 2.0 SPS02 and was successfully able to install and use SHINE with that version.
Happy holiday season,
John

**Comment by CHERIANS** [comment]
Hi John,
Thanks for the quick update and wishes. Wish you also happy holidays.
Best Regards
Stephen
