### ISSUE TITLE
 java module fails

### ISSUE THREAD

**Issue by draschke** [SAP/hana-shine-xsa#9]
Hi,
got your described error with 1.2.2. Changed the version to 1.2.1., but got the same problem.
<sap.gateway.version>1.2.1</sap.gateway.version>

[ERROR] Failed to execute goal on project sap-xsac-shine-user-java: Could not resolve dependencies for project com.sap.refapps:sap-xsac-shine-user-java:war:1.3.3: The following artifacts could not be resolved: com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.2.1, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core:jar:1.2.1, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.jdbc:jar:1.2.1, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.cds:jar:1.2.1, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.core.web:jar:1.2.1, com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.xsa:jar:1.2.1: Could not find artifact com.sap.gateway.v4.rt:com.sap.gateway.v4.rt.api:jar:1.2.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by draschke** [comment]
We are on SAP HANA XSA WebIDE 2.0 SPS 2
Cloned the Shine project from here.

**Comment by CHERIANS** [comment]
Hi,
Can you open Web IDE -> Go to About -> Help and let me know the Build version
Best Regards
Stephen

**Comment by draschke** [comment]
Version: SAP Web IDE for HANA 2 
SPS 01 Patch 2 ( Build 4.1.46 )

**Comment by draschke** [comment]
Got it to run with 1.2.3.
<sap.gateway.version>1.2.3</sap.gateway.version>

Used "Show dependency updates" and it was building successfully.
Does "Show dependency updates" also works for java?

**Comment by CHERIANS** [comment]
Great. Thanks for the update. Yes show dependency updates seems to work for me as well for java
Best Regards
Stephen
